import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Green Huang - Next.js beginner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <div>
        <header className="flex justify-between items-center p-4">
            <h1 className="text-2xl font-bold">
                <a href="/">
                    Green's homepage
                </a>
            </h1>
            <nav>
                <ul className="flex space-x-4">
                    <li>
                        <a href="/performance" className="text-blue-500 hover:underline">
                            performance
                        </a>
                    </li>
                    <li>
                        <a href="/reliability" className="text-blue-500 hover:underline">
                            reliability
                        </a>
                    </li>
                    <li>
                        <a href="/scale" className="text-blue-500 hover:underline">
                            scale
                        </a>
                    </li>
                </ul>
            </nav>
        </header>
    </div>

    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    {children}
    </body>

    </html>
  );
}
